name: Build and deploy Python app to Azure Web App - produccionweb

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Create virtual environment and install dependencies
        run: |
          python -m venv antenv
          source antenv/bin/activate
          pip install -r backend/requirements.txt

      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: |
            .
            !./antenv/
            !./frontend/
            !./migrations/
            !./scripts/
            !./docker-compose.yml
            !./README.md
            !./promt_init.txt
            !./.github/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_702494534395415DB424AC1F40045D8A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_25B684984D0F4F56AACF029D6B28B315 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_98CB9B7F331A4E2B8327960A376CB73E }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'produccionweb'
          slot-name: 'Production'
          package: '.'
